### ISSUE TITLE
File not created

### ISSUE THREAD

**Issue by Chappy59711** [MooseDojo/apt2#15]
When I run the program, I receive the following:

Scan file saved to [/opt/apt2/proofs/NMAP-nmapScan10.0.2.16/32-modpvsftux]
*** print_tb:
  File "./apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])

*** print_exception:
Traceback (most recent call last):
  File "./apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/opt/apt2/core/framework.py", line 675, in run
    self.displayMenu()
IOError: [Errno 2] No such file or directory: '/opt/apt2/proofs/NMAP-nmapScan10.0.2.16/32-modpvsftux.xml'

*** print_exc:
Traceback (most recent call last):
  File "./apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/opt/apt2/core/framework.py", line 675, in run
    self.displayMenu()
  File "/opt/apt2/core/framework.py", line 448, in displayMenu
    self.runScan()
  File "/opt/apt2/core/framework.py", line 470, in runScan
    flags="-s" + self.config["scan_type"] + " " + self.config["scan_flags"], vector="nmapScan", filetag="nmapScan" + self.config["scan_target"])
  File "/opt/apt2/core/mynmap.py", line 32, in run
    return self.loadXMLFile(self.outfile + ".xml", "nmapFile")
  File "/opt/apt2/core/mynmap.py", line 36, in loadXMLFile
    with open(file, "r") as fd:
IOError: [Errno 2] No such file or directory: '/opt/apt2/proofs/NMAP-nmapScan10.0.2.16/32-modpvsftux.xml'

Thanks,

**Comment by crdotson** [comment]
It worked for me just a single IP but not with a CIDR suffix of /24 or /32.

**Comment by tatanus** [comment]
this has now been corrected.  Please grab the latest copy and it should now work.
