### ISSUE TITLE
Initial dependency

### ISSUE THREAD

**Issue by pand0rausa** [MooseDojo/apt2#17]
On doing an initial git clone on Debian there is a missing dependency. 

Traceback (most recent call last):
  File "./apt2.py", line 11, in <module>
    from core.framework import Framework
  File "/home/user/Applications/Network/apt2/core/framework.py", line 12, in <module>
    from mymsf import myMsf
  File "/home/user/Applications/Network/apt2/core/mymsf.py", line 4, in <module>
    import core.msfrpc2 as msfrpc
  File "/home/user/Applications/Network/apt2/core/msfrpc2.py", line 16, in <module>
    import msgpack
ImportError: No module named msgpack

This will resolve the issue and allow the program to start (May need to include in the INSTALL?):
sudo apt-get install python-msgpack

**Comment by tatanus** [comment]
I update the affected file, in the case that msgpack is not found, to now display:

[!] Install the msgpack library: pip install msgpack-python

This should satisfy the issue you encountered
