### ISSUE TITLE
Error when scanning - Responder

### ISSUE THREAD

**Issue by theabraxas** [MooseDojo/apt2#18]
When attempting to scan from files:

[*] Starting responder...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/tools/apt2/core/actionModule.py", line 57, in go
    return self.process()
  File "/root/tools/apt2/modules/action/responder.py", line 55, in process
    method = record[1]
IndexError: list index out of range

**Comment by alane-r7** [comment]
If responder doesn't find anything Responder.db doesn't get created, accounted for this in some length/content checks.

**Comment by theabraxas** [comment]
Awesome, thanks man!
