### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Teicu** [MooseDojo/apt2#24]
Hi, can you help me with this error please? Thank you

~/apt2# ./apt2.py -v -v -b -s 1 -f demo.xml
Traceback (most recent call last):
  File "./apt2.py", line 14, in <module>
    framework = Framework()
  File "/root/apt2/core/framework.py", line 40, in __init__
    self.config['lhost'] = Utils.getIP()
  File "/root/apt2/core/utils.py", line 148, in getIP
    ip = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -5] No address associated with hostname

**Comment by tatanus** [comment]
What can you tell us about your environment?  Linux? Which distribution? How many ips are defined? Does the system have a defined hostname?

**Comment by tatanus** [comment]
Just pushed out a new code change that should properly handle your situation.  I would suggest that you make use of the "--ip" command line flag to specify your desired IP address.

Please let us know if the latest code updates do not properly handle your issue.
