### ISSUE TITLE
Initial Run Issue

### ISSUE THREAD

**Issue by chess1669** [MooseDojo/apt2#25]
Most Recent Kali Linux Dist

[*] Scan file saved to [/root/apt2/proofs/NMAP-nmapScan192.168.1.148-snedhaqfcb]
*** print_tb:
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])

*** print_exception:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 703, in run
    self.displayMenu()
IOError: [Errno 2] No such file or directory: '/root/apt2/proofs/NMAP-nmapScan192.168.1.148-snedhaqfcb.xml'

*** print_exc:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 703, in run
    self.displayMenu()
  File "/root/apt2/core/framework.py", line 454, in displayMenu
    self.runScan()  # Skip first trip through menu and go straight into a scan using whatever arguments were
  File "/root/apt2/core/framework.py", line 495, in runScan
    flags="-s" + self.config["scan_type"] + " " + self.config["scan_flags"], vector="nmapScan", filetag="nmapScan" + self.config["scan_target"])
  File "/root/apt2/core/mynmap.py", line 33, in run
    return self.loadXMLFile(self.outfile + ".xml", "nmapFile")
  File "/root/apt2/core/mynmap.py", line 37, in loadXMLFile
    with open(file, "r") as fd:
IOError: [Errno 2] No such file or directory: '/root/apt2/proofs/NMAP-nmapScan192.168.1.148-snedhaqfcb.xml'

**Comment by tatanus** [comment]
Can you please provide the commandline (including arguments)?

As well as the top 30 or so lines of the output?

This will help us be able to identify the cause of the issue.

**Comment by chess1669** [comment]
root@kali1669:~/apt2# python apt2.py -f 192.168.1.0/24


*** print_tb:
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])


*** print_exception:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 685, in run
    self.parseParameters(argv)
IOError: [Errno 2] No such file or directory: '192.168.1.0/24'


*** print_exc:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 685, in run
    self.parseParameters(argv)
  File "/root/apt2/core/framework.py", line 247, in parseParameters
    type = self.idFileType(f)
  File "/root/apt2/core/framework.py", line 438, in idFileType
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '192.168.1.0/24'

**Comment by chess1669** [comment]
Seems to be nothing being outputted to proofs. Sorry for my lack of knowledge, but I really appreciate you assisting me getting this up and running.

**Comment by chess1669** [comment]
If i am misunderstanding "top 30 or so lines of the output" please let me know where I can locate this and I will post the information for you. thanks again

**Comment by tatanus** [comment]
When I said the top 30 or so lines of output I mean, the top 30 or so lines of output from the tool...   as in including the banner and all when you run it.

also try running with the bypassmenu and verbose flags such as:

python apt2.py -v -v -b -f 192.168.1.0/24

**Comment by chess1669** [comment]
With the bypassmenu and verbose flags:

root@kali1669:~/apt2# python apt2.py -v -v -b -f 192.168.1.0/24
** print_tb:
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])


*** print_exception:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 685, in run
    self.parseParameters(argv)
IOError: [Errno 2] No such file or directory: '192.168.1.0/24'


*** print_exc:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 685, in run
    self.parseParameters(argv)
  File "/root/apt2/core/framework.py", line 247, in parseParameters
    type = self.idFileType(f)
  File "/root/apt2/core/framework.py", line 438, in idFileType
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '192.168.1.0/24'


Output from the tool:
root@kali1669:~/apt2# python ./apt2.py
[*] 
[*]       dM.    `MMMMMMMb. MMMMMMMMMM      
[*]      ,MMb     MM    `Mb /   MM   \      
[*]      d'YM.    MM     MM     MM   ____   
[*]     ,P `Mb    MM     MM     MM  6MMMMb  
[*]     d'  YM.   MM    .M9     MM MM'  `Mb 
[*]    ,P   `Mb   MMMMMMM9'     MM      ,MM 
[*]    d'    YM.  MM            MM     ,MM' 
[*]   ,MMMMMMMMb  MM            MM   ,M'    
[*]   d'      YM. MM            MM ,M'      
[*] _dM_     _dMM_MM_          _MM_MMMMMMMM 
[*] 
[*] 
[*] An Automated Penetration Testing Toolkit
[*] Written by: Adam Compton & Austin Lane
[*] Verion: 1.0.0
WARNING: No route found for IPv6 destination :: (no default route?)
[!] Module 'hydrasmbpassword' disabled:
[!]      Safety_Level (2) is below requirement: 4
[!] Module 'responder' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_jboss_maindeployer' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_tomcat_mgr_upload' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'searchnfsshare' disabled:
[!]      Module Manually Disabled !!!
[*] Input Modules Loaded:	1
[*] Action Modules Loaded:	37
[*] Report Modules Loaded:	1
[*] 
[*] The KnowledgeBase will be auto saved to : /root/apt2/proofs/KB-vfwilzcjeq.save
[*] Local IP is set to : 192.168.1.150
[*]       If you would rather use a different IP, then specify it via the [--ip <ip>] argument.
[*] 
[*] ---------------------------------------
[*] 
[*] 1. Run
[*] 2. NMAP Settings
[*] 3. Browse KB
[*] 4. Quit
[*] 
[?] Select an option: 


I could be missing something blatantly obvious, as I am new to this. My apologies.

**Comment by chess1669** [comment]
So I was able to get this far. KB in Proofs folder were made, and report was compiled. As soon as I issue a target though, I get those aforementioned errors.

root@kali1669:~/apt2# ./apt2.py -b
[*] 
[*]       dM.    `MMMMMMMb. MMMMMMMMMM      
[*]      ,MMb     MM    `Mb /   MM   \      
[*]      d'YM.    MM     MM     MM   ____   
[*]     ,P `Mb    MM     MM     MM  6MMMMb  
[*]     d'  YM.   MM    .M9     MM MM'  `Mb 
[*]    ,P   `Mb   MMMMMMM9'     MM      ,MM 
[*]    d'    YM.  MM            MM     ,MM' 
[*]   ,MMMMMMMMb  MM            MM   ,M'    
[*]   d'      YM. MM            MM ,M'      
[*] _dM_     _dMM_MM_          _MM_MMMMMMMM 
[*] 
[*] 
[*] An Automated Penetration Testing Toolkit
[*] Written by: Adam Compton & Austin Lane
[*] Verion: 1.0.0
WARNING: No route found for IPv6 destination :: (no default route?)
[!] Module 'hydrasmbpassword' disabled:
[!]      Safety_Level (2) is below requirement: 4
[!] Module 'responder' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_jboss_maindeployer' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_tomcat_mgr_upload' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'searchnfsshare' disabled:
[!]      Module Manually Disabled !!!
[*] Input Modules Loaded:	1
[*] Action Modules Loaded:	37
[*] Report Modules Loaded:	1
[*] 
[*] The KnowledgeBase will be auto saved to : /root/apt2/proofs/KB-usdonkiiye.save
[*] Local IP is set to : 192.168.1.150
[*]       If you would rather use a different IP, then specify it via the [--ip <ip>] argument.
[*] Use the following controls while scans are running:
[*] Generating Reports
[*] - p - pause/resume event queueing
[*] Report file located at /root/apt2/reports/reportGenHTML_jadheqjthn.html
[*] 
[*] Good Bye!
[*] Current # of Active Threads = [0]
[*]     ==>

**Comment by tatanus** [comment]
Sorry for the delay, but I just saw your error.   you are specifying a target range with the "-f" option.  The "-f" is used to specify a source nmap.xml file.  You want to use the "--target" flag instead, you can see this if you run:

python apt2.py -h

So the command line you should be using is:

python apt2.py -v -v -b --target 192.168.1.0/24

try that and see if it works.

**Comment by chess1669** [comment]
root@kali1669:~/apt2# python apt2.py -v -v -b --target 192.168.1.0/24
[*] 
[*]       dM.    `MMMMMMMb. MMMMMMMMMM      
[*]      ,MMb     MM    `Mb /   MM   \      
[*]      d'YM.    MM     MM     MM   ____   
[*]     ,P `Mb    MM     MM     MM  6MMMMb  
[*]     d'  YM.   MM    .M9     MM MM'  `Mb 
[*]    ,P   `Mb   MMMMMMM9'     MM      ,MM 
[*]    d'    YM.  MM            MM     ,MM' 
[*]   ,MMMMMMMMb  MM            MM   ,M'    
[*]   d'      YM. MM            MM ,M'      
[*] _dM_     _dMM_MM_          _MM_MMMMMMMM 
[*] 
[*] 
[*] An Automated Penetration Testing Toolkit
[*] Written by: Adam Compton & Austin Lane
[*] Verion: 1.0.0
WARNING: No route found for IPv6 destination :: (no default route?)
[!] Module 'hydrasmbpassword' disabled:
[!]      Safety_Level (2) is below requirement: 4
[!] Module 'responder' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_jboss_maindeployer' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'msf_tomcat_mgr_upload' disabled:
[!]      Safety_Level (3) is below requirement: 4
[!] Module 'searchnfsshare' disabled:
[!]      Module Manually Disabled !!!
[*] Input Modules Loaded:	1
[*] Action Modules Loaded:	37
[*] Report Modules Loaded:	1
[*] 
[*] The KnowledgeBase will be auto saved to : /root/apt2/proofs/KB-wrhbjaqqkl.save
[*] Local IP is set to : 192.168.1.150
[*]       If you would rather use a different IP, then specify it via the [--ip <ip>] argument.
[*] Scan file saved to [/root/apt2/proofs/NMAP-nmapScan192.168.1.0_24-ltvefbwcpt]
*** print_tb:
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])


*** print_exception:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 715, in run
    self.displayMenu()
IOError: [Errno 2] No such file or directory: '/root/apt2/proofs/NMAP-nmapScan192.168.1.0_24-ltvefbwcpt.xml'


*** print_exc:
Traceback (most recent call last):
  File "apt2.py", line 16, in <module>
    framework.run(sys.argv[1:])
  File "/root/apt2/core/framework.py", line 715, in run
    self.displayMenu()
  File "/root/apt2/core/framework.py", line 466, in displayMenu
    self.runScan()  # Skip first trip through menu and go straight into a scan using whatever arguments were
  File "/root/apt2/core/framework.py", line 507, in runScan
    flags="-s" + self.config["scan_type"] + " " + self.config["scan_flags"], vector="nmapScan", filetag="nmapScan" + self.config["scan_target"])
  File "/root/apt2/core/mynmap.py", line 33, in run
    return self.loadXMLFile(self.outfile + ".xml", "nmapFile")
  File "/root/apt2/core/mynmap.py", line 37, in loadXMLFile
    with open(file, "r") as fd:
IOError: [Errno 2] No such file or directory: '/root/apt2/proofs/NMAP-nmapScan192.168.1.0_24-ltvefbwcpt.xml'

**Comment by chess1669** [comment]
any ideas? I don't want to waste your time, so I won't bother you again sorry. Apologize, just trying to get my feet wet.

**Comment by tatanus** [comment]
I am traveling internationally at the moment.  Once I get to a stable internet connection, I will be able to look at this issue again.  Sorry for the delay.

**Comment by tatanus** [comment]
I have not been able to reproduce your error.  If you are still encountering it, please let me know.

**Comment by Kolano** [comment]
Unclear about the initial poster's specific errors, but have seen similar "No such file or directory" apparently related to permission issues. Running APT2 with root permissions via sudo seems to resolve issues.

**Comment by tatanus** [comment]
Thank you for your response.  I will look into this more as time allows.

On a side note, we are actively developing a newer and hopefully more stable version of APT2 over the next couple months.  Please keep an eye out for it.
