### ISSUE TITLE
NameError: global name 'outfile' is not defined

### ISSUE THREAD

**Issue by jonaslejon** [MooseDojo/apt2#28]
Hello, got the following exception:
```
[*] [VERBOSE] httpOptions - Connecting to 10.0.1.13
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/apt2/core/actionModule.py", line 63, in go
    return self.process()
  File "/root/apt2/modules/action/searchftp.py", line 89, in process
    self.testTarget(t, 21)
  File "/root/apt2/modules/action/searchftp.py", line 70, in testTarget
    success = self.searchTarget(host, port, "anonymous", "anon@ymo.us")
  File "/root/apt2/modules/action/searchftp.py", line 60, in searchTarget
    kb.add("host/" + target + "/files/" + self.shortName + "/" + outfile.replace("/", "%2F"))
NameError: global name 'outfile' is not defined
```

**Comment by tatanus** [comment]
sorry for the delay.  That line should have been commented out for now.  I will be using that when I work on it again later, but for now I just commented out the line as it is not needed.
