### ISSUE TITLE
unable to start apt2

### ISSUE THREAD

**Issue by hanifzameri** [MooseDojo/apt2#52]
i've tried and installed all the dependancies in the wiki, apt2 still can't start im new to this and trying to experiment with your tools, any help is appreciated. below is the error that I got when I run python apt2.py:

python apt2.py -h
Traceback (most recent call last):
  File "apt2.py", line 9, in <module>
    from core.framework import Framework
  File "/root/apt2/core/framework.py", line 14, in <module>
    from keystore import KeyStore as kb
  File "/root/apt2/core/keystore.py", line 5, in <module>
    sys.exit("[!] Install the UnQlite library: pip install unqlite") 
NameError: name 'sys' is not defined

And when I try to install pip, i got this error:

 ----------------------------------------
  Failed building wheel for unqlite
  Running setup.py clean for unqlite
Failed to build unqlite
Installing collected packages: unqlite
  Running setup.py install for unqlite ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zSjpXt/unqlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-QehW7p-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'unqlite' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-j9xj4T/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c unqlite.c -o build/temp.linux-x86_64-2.7/unqlite.o
    unqlite.c:20:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
any help is appreciated

**Comment by acompton-r7** [comment]
my apologies

there was a missing import in core/keystore.py and the wiki was missing a step in the stall.  You need to install cython prior to trying to install unqlite.


```
pip install cython

then

pip install unqlite
```

Here is the output of when I tried to install it on a new system.

```
root:~/apt2# pip install unqlite
Collecting unqlite
  Downloading unqlite-0.6.2.tar.gz (561kB)
    100% |████████████████████████████████| 563kB 835kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-q2sBs1/unqlite/setup.py", line 7, in <module>
        raise RuntimeError('Cython must be installed to build unqlite-python.')
    RuntimeError: Cython must be installed to build unqlite-python.

root:~/apt2# pip install cython                                                                                                                   
Collecting cython                                                                                                                                                            
  Downloading Cython-0.28.1-cp27-cp27mu-manylinux1_x86_64.whl (3.3MB)                                                                                                        
    100% |████████████████████████████████| 3.3MB 136kB/s                                                                                                                    
Installing collected packages: cython                                                                                                                                        
Successfully installed cython-0.28.1                                                                                                                                         
                                                                                                 
root:~/apt2# pip install unqlite                                                                                                                  
Collecting unqlite                                                                                                                                                           
  Using cached unqlite-0.6.2.tar.gz                                                                                                                                          
Requirement already satisfied (use --upgrade to upgrade): Cython in /usr/local/lib/python2.7/dist-packages (from unqlite)                                                    
Building wheels for collected packages: unqlite                                                                                                                              
  Running setup.py bdist_wheel for unqlite ... done                                                                                                                          
  Stored in directory: /root/.cache/pip/wheels/74/29/ab/edccb9cb08e4db97068fd968dd6266ecacb363d93ff53ecc6c                                                                   
Successfully built unqlite                                                                                                                                                   
Installing collected packages: unqlite                                                                                                                                       
Successfully installed unqlite-0.6.2 

root:~/apt2# python apt2.py -h
usage: apt2.py [-h] [-C <config.txt>] [-f [<input file> [<input file> ...]]]
               [--target] [--ip <local IP>] [-v] [-s SAFE_LEVEL]
               [-x EXCLUDE_TYPES] [--listmodules]

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbosity       increase output verbosity
  -s SAFE_LEVEL, --safelevel SAFE_LEVEL
                        set min safe level for modules. 0 is unsafe and 5 is
                        very safe. Default is 4
  -x EXCLUDE_TYPES, --exclude EXCLUDE_TYPES
                        specify a comma seperatec list of module types to
                        exclude from running

inputs:
  -C <config.txt>       config file
  -f [<input file> [<input file> ...]]
                        one of more input files seperated by spaces
  --target              initial scan target(s)

advanced:
  --ip <local IP>       defaults to 167.99.10.110

misc:
  --listmodules         list out all current modules and exit

```
